import { Toaster } from "react-hot-toast";
import { Footer, Navbar } from "./components";
import "./globals.css";
import Providers from "@/reduxStore/Providers";
export const metadata = {
  title: "Panda Stores",
  description: "Generated by Abdelrahman Elrefai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="layout">
          <Providers>
            <Toaster />
            <header>
              <Navbar />
            </header>
            <div className="main-container">
              {children}
            </div>
            <footer>
              <Footer />
            </footer>
          </Providers>
        </div>
      </body>
    </html>
  );
}
