import { Footer, Navbar } from "./components";
import "./globals.css";
import Head from "next/head";
export const metadata = {
  title: "Ecommerce APP",
  description: "Generated by Abdelrahman Elrefai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="layout">
        <header>
          <Navbar /> 
        </header>
        <div className="main-container">
          {children}
        </div>
        <footer>
          <Footer />
        </footer>
        </div>
        </body>
    </html>
  );
}
