import "./globals.css";

export const metadata = {
  title: "Ecommerce APP",
  description: "Generated by Abdelrahman Elrefai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
